### ISSUE TITLE
[frontend] Export profile

### ISSUE THREAD

**Issue by ouchadam** [lesspass/lesspass#154] opened 2017-02-26 00:23 UTC
As a user I would like to export my profiles so that I can back them up without having to manually host lesspass.

Being able to directly export a profile to json like the format [the blog post mentions](https://blog.lesspass.com/lesspass-how-it-works-dde742dd18a4#.a4wqgitkl) would be perfect 😄 

```json
{
    "id": "40d31aef-7f91-8bc9-41ce-2f47477ad8c4",
    "login": "38491092",
    "site": "www.ingdirect.fr",
    "lowercase": false,
    "uppercase": false,
    "symbols": false,
    "numbers": true,
    "counter": 1,
    "length": 6,
    "created": "2016-10-10T12:15:17.354990Z",
    "modified": "2016-10-10T12:15:17.355023Z"
}
```

**Comment by guillaumevincent** [comment] 2017-02-26 10:21
Hi ouchadam,
maybe we can export all password profiles instead of one?

**Comment by ouchadam** [comment] 2017-02-26 10:49
that would be great 👍 

Being able to export profiles from the anonymous [LessPass](https://lesspass.com/#/) password generator could be useful as well!

**Comment by edouard-lopez** [comment] 2017-02-27 19:44
@ouchadam could you elaborate on the _why_ you want to back them up. 

Did you had trouble managing your profiles ? If so, what were trying to achieve and how did the current version fails you?

Just to be sure, are you aware of the [_connected mode_](https://github.com/lesspass/lesspass/releases/tag/aurora)?

**Comment by Kcchouette** [comment] 2017-03-29 09:57
To use the connected mode, we should have a server OR to use lesspass.com.
I'm using this kind of JSON file to remember the option, because I do not want to use lesspass.com and because I don't have any server.

I have this file in USB key and in local to always have this file.

```
[{
	"site": "",
	"login": "",
	"lowercase": true,
	"uppercase": true,
	"numbers": true,
	"symbols": true,
	"length": 16,
	"counter": 1
}]
```

**Comment by guillaumevincent** [comment] 2017-03-29 13:22
@Kcchouette can you describe your workflow on a new device?
How do you imagine the saving process and the loading process.

It will helps us to build better user experience
thanks

**Comment by Kcchouette** [comment] 2017-03-29 13:54
@guillaumevincent yes, but it's my workflow

1. installing lesspass
2. if device is mine, putting through usb the file in my hard drive disk; else I prefer to use my smartphone

The problem is when I should create something when I'm not on my computer...

I'm a new user, so I'm still thinking about how to easily share this file but I think I'll put in a cloud instance.

Why not doing like uBlock: a backup/recover JSON file and, if the user want, use the cloud storage of the browser? https://github.com/gorhill/uBlock/wiki/Cloud-storage

**Comment by guillaumevincent** [comment] 2017-03-29 15:35
@Kcchouette with this little exercise you see that you need to solve a 'sync' problem already solve by LessPass Database.
The second problem is a trusted problem. You trust Firefox server and no LessPass Database server. No problem with that 😃 

Maybe we should go in cloud storage direction, instead of local storage.
But this is a different issue

**Comment by Kcchouette** [comment] 2017-03-29 21:20
@guillaumevincent Yes, indeed, I finally choose a cloud provider to host my json file. But in the future, why not incorporate plug-in/add-on which connect to a cloud provider (like it's done I think in cozy)
For the second problem, in my opinion, a older service is more trustable than a newer one (on the duration).

**Comment by guillaumevincent** [comment] 2017-04-03 07:59
Hello,

The discussion showed that this feature forces people to have a way to synchronize this file. This is in contradiction with our vision of the product. We created LessPass to avoid having to sync anything.

If you really want to save password in a file and sync it you have 3 options:

 * open web console > network tab > right click on `/api/passwords/` copy response > paste on a json file
![screenshot from 2017-04-03 09-47-11](https://cloud.githubusercontent.com/assets/943762/24599911/a2a0dc46-1852-11e7-88d6-f280fd2f650f.png)
 * curl directly in terminal (replace email, password and YOUR_TOKEN with yours)

```
$ curl -X POST -H "Content-Type: application/json" -d '{"email":"...","password":"..."}' https://lesspass.com/api/tokens/auth/
{"token":"YOUR_TOKEN"}
$ curl -H "Authorization: JWT YOUR_TOKEN" https://lesspass.com/api/passwords/ > profiles.json```

I close this one

**Closed by guillaumevincent** 2017-04-03 07:59 UTC
Labels: IDEA

**Comment by Kcchouette** [comment] 2017-04-03 09:16
@guillaumevincent for me, it's the case. The goal of this issue was to offer an alternative to `lesspass` cloud provider to save our settings and our own server (build using docker) that we don't have.
In these two same cases (lesspass cloud provider & server), we save a JSON file.

The goal of this issue is to add a way to save this JSON file in the cloud-provider you want (and to not restrict to two services) or to save in the way you want.

It's not something you should build to force people, but to offer this opportunity to save the settings (if people doesn't want to do it, they just have to not download the file, for example)

**Comment by Kcchouette** [comment] 2017-04-03 09:17
@guillaumevincent moreover, the first and second options are using lesspass cloud provider, that I don't want to use, and instead use my nextcloud instance

**Comment by ouchadam** [comment] 2017-04-03 09:36
like @Kcchouette mentioned, this feature request was originally created because I do not want to host a server or trust the lesspass website, I am totally behind the concept of password generation from multiple variables instead of password syncing. 

My concern is that a password is tightly coupled to the profile used at the time of generation, if the website decides one day to change date format of the `created/modified` timestamps (perhaps it reads from the machine locale) a password would no longer be correctly recreated.

I can understand why you want to keep things simple and enforce lesspass for syncing, but in my case the main appeal was that this could be a decentralised password solution 😸

**Comment by guillaumevincent** [comment] 2017-04-03 09:50
> My concern is that a password is tightly coupled to the profile used at the time of generation, if the website decides one day to change date format of the created/modified timestamps (perhaps it reads from the machine locale) a password would no longer be correctly recreated.

It's a misconception of the way password are generated. Password generator don't use created and updated field. Here a graph to understand how your passwords are generated.
![screenshot from 2017-04-03 11-39-16](https://cloud.githubusercontent.com/assets/943762/24603717/3331e6a6-1862-11e7-9039-2b1fac90b9a7.png)

> I can understand why you want to keep things simple and enforce lesspass for syncing, but in my case the main appeal was that this could be a decentralised password solution 😸

We don't want to enforce LessPass for syncing, we want to **remove the need to sync passwords**.

> this feature request was originally created because I do not want to host a server or trust the lesspass website

I'm totally ok with that, but those are the only solutions we have actually to sync password profiles between devices (self host or https://lesspass.com).

You want us to add another solution to help you to sync password profiles between devices. As I said, the json file solution will force you to add another third party in the loop. The storage provider (dropbox, google drive, usb)

And I created LessPass to remove from my need those storage provider. So I hope you understand this feature is not going in the right direction. We created LessPass to remove the need to sync storage provider.

When you describe your use cases, I feel you are looking for more a tool like KeePass.
If you don't know KeePass, try a look https://www.keepassx.org/

Best

**Comment by kidburglar** [comment] 2017-04-03 11:27
Hello,
I don't really understand the link between "sync passwords" and backup configuration.

If you prefer look at Ublock extension they have an option to export the configuration in a file and to load it back. I asked for something similar, nothing less or more.

Cheers.

**Comment by guillaumevincent** [comment] 2017-04-03 11:31
@kidburglar are you talking about backup default options? @ouchadam and @Kcchouette are talking about password profiles.

They asked for a json file with all password profiles to use it between different devices == sync password profiles

**Comment by ouchadam** [comment] 2017-04-03 11:42
@guillaumevincent no problem! 😄 I appreciate that you're driving the product in the direction of your vision and responding to issues/feature requests  👍

**Comment by Kcchouette** [comment] 2017-04-03 11:45
> Our long-term goal is to not need storage to remove the synchronization problem.

Yes, I understand that this feature is not really in the direction of you want.

@kidburglar we're speaking here about an alternative of the "connected mode", ie the right to save the password’s profile (if you use uppercase, lowercase, etc) –except the master password and the generated password– to be able to generate the password.

> As I said, the json file solution will force you to add another third party in the loop

Yes, like for example self hosting or https://lesspass.com. So I just want to add other choice than theses two.

**Comment by kidburglar** [comment] 2017-04-03 11:50
@guillaumevincent @Kcchouette 
Ah ok, I missunderstand it.
I thought that the password profiles we're stored locally like the default options.

**Comment by Kcchouette** [comment] 2017-04-03 16:43
@guillaumevincent here something like a demo to show you what I've build doing the thing I want: https://kcchouette.github.io/lesspass-helper/

1. You go on the url
2. You enter that in json file (for the demo)
```
[{
	"site": "github.com",
	"login": "guillaumevincent",
	"lowercase": true,
	"uppercase": true,
	"numbers": true,
	"symbols": false,
	"length": 8,
	"counter": 1
}]
```
3. You click on lesspassLink

You can add password's profile too, and that will update your json file.

All sources are on https://github.com/Kcchouette/lesspass-helper (you can use it and improve it if you want @ouchadam @kidburglar )

**Comment by guillaumevincent** [comment] 2017-04-03 16:58
@Kcchouette this is one of the force of open source project. You can fork it to fit your need.

Maybe an easy way is to fork lesspass-pure and load your json in localStorage passwords field see https://github.com/lesspass/pure/blob/fc21a0612f1300fa383d84fa65d1fab84a1a23f5/src/store/index.js 

`JSON.parse(localStorage.getItem('lesspass')).passwords`

Go on https://lesspass.com, open the console and see localStorage for lesspass:

`JSON.stringify(JSON.parse(localStorage.getItem('lesspass')), null,2)`

**Comment by Kcchouette** [comment] 2017-04-03 17:04
@guillaumevincent sorry I don't understand at all the easy way you are talking about.

Can you give me more detail please?

**Comment by guillaumevincent** [comment] 2017-04-03 17:19
lesspass use localStorage when connected.
Maybe you can "modify" lesspass-pure (the composant used everywhere) to fill `passwords` array in local storage with your json.

To see the structure of the localStorage, you can open https://lesspass.com and inspect localStorage in the console.

**Comment by major0** [comment] 2018-09-25 17:10
I am aware that this issue is closed, though I admit I ran across the issue in trying to find an easy way to _load_ profiles from a file (for use with phones, browsers, and the CLI tool). I still feel that there is something missing in part of this discussion, or perhaps my use case just mangles this a bit (or I am doing something wrong).

My partner and I use LessPass as a means for sharing authentication credentials, so we share the Master Password (only ever stored in our noggin).  A core problem for us becomes synchronizing the Profile data between all of our devices.  To that end, the Less Pass Profile has _functionally_ become the equivalent of a shared password.

Currently we rely on a fairly manual process to track/update the profile information via a private Keybase share (which is available to all devices which can run LessPass), so for us the ability to specify a profile file would seem to be useful (unless there is an alternative that I am not grok'ing).

**Comment by guillaumevincent** [comment] 2018-09-25 17:59
@major0 why not using LessPass Database with the same login?

**Comment by major0** [comment] 2018-09-25 18:29
> @major0 why not using LessPass Database with the same login?

@guillaumevincent That dawned on me directly after submitting my post... Though I suspect we will be storing backups of the profiles in Keybase still, in case the LastPass database is ever lost.

**Comment by major0** [comment] 2018-09-25 18:46
That raises the question .. and this likely belongs in its own issue.  Would it be possible to support import/export of profiles to/from the LessPass Database for the purpose of backup/recovery?

**Comment by major0** [comment] 2018-09-25 20:14
Found the solution: https://github.com/lesspass/lesspass/wiki/password-profiles-manipulation-scripts

Though it makes me wonder, couldn't this solution be added to the lesspass cli as something like:

```
lesspass lesspass.com user@domain --backup=backup.json
lesspass lesspass.com user@domain --recover=backup.json
```
