### ISSUE TITLE
LessPass extension not working on Tor Browser

### ISSUE THREAD

**Issue by alu0100892833** [lesspass/lesspass#213] opened 2017-04-25 15:40 UTC
Hi. I installed the **Firefox extension** in the **Tor Browser**; since one is based on the other, I figured that there shouldn´t be any problems. However, although the extension is installed, when I click the icon to open it, it starts loading but never ends doing it. I cannot use it.
Is there any way to solve this or should I forget using this extension in Tor Browser?

**Comment by guillaumevincent** [comment] 2017-04-27 19:52
@alu0100892833 strange issue, I need to install Tor browser to test this

**Comment by guillaumevincent** [comment] 2017-04-27 20:45
![screenshot from 2017-04-27 22-43-08](https://cloud.githubusercontent.com/assets/943762/25503499/f6bfb7ce-2b9a-11e7-99ff-06744206c047.png) I could install it but the generation doesn't seems to work

**Comment by guillaumevincent** [comment] 2017-04-27 20:59
@alu0100892833 so Tor browser support webcrypto but don't implement `Buffer`
This is a definitively a bug. Don't understand why they remove Buffer object on Tor Browser.

![screenshot from 2017-04-27 22-52-56](https://cloud.githubusercontent.com/assets/943762/25504125/05316c7e-2b9d-11e7-8a2d-30c1ab3ed59c.png)

**Comment by guillaumevincent** [comment] 2017-04-27 21:11
I close this one and I created a dedicated issue: https://github.com/lesspass/lesspass/issues/216

**Comment by guillaumevincent** [comment] 2017-04-29 09:01
@alu0100892833 webcrypto failed on Tor Browser and raise an operation error. See https://diafygi.github.io/webcrypto-examples/.
We can't catch the error and fallback on browserified pbkdf2.
I don't know why the implementation is different from Firefox. But it looks like an error in Tor Browser web crypto implementation.

**Comment by guillaumevincent** [comment] 2017-04-29 09:07
try in Tor console:
```
window.crypto.subtle.importKey(
  "raw",
  window.crypto.getRandomValues(new Uint8Array(16)),
  {
    name: "PBKDF2",
  },
  false,
  ["deriveKey", "deriveBits"]
)
  .then(function(key) {
    window.crypto.subtle.deriveKey(
      {
        "name": "PBKDF2",
        salt: window.crypto.getRandomValues(new Uint8Array(16)),
        iterations: 1000,
        hash: {name: "SHA-256"},
      },
      key,
      {
        name: "AES-CTR",

        length: 256,
      },
      false,
      ["encrypt", "decrypt"]
    )
      .then(function(key) {
        //returns the derived key
        console.log(key);
      })
      .catch(function(err) {
        console.error(err);
      });

  })
  .catch(function(err) {
    console.error(err);
  });
```

**Comment by guillaumevincent** [comment] 2017-04-29 09:17
I can reproduce the bug on travis: https://travis-ci.org/lesspass/core

**Comment by guillaumevincent** [comment] 2017-04-29 09:31
Ok so Tor Browser is based on Firefox 45. And Firefox webcrypto support pbkdf2 sha-256 since Firefox 47 (https://bugzilla.mozilla.org/show_bug.cgi?id=1238277)

**Comment by guillaumevincent** [comment] 2017-04-29 09:56
Ok @alu0100892833 so Tor Browser version 7 is in alpha and based on Firefox 52. So this will be fixed soon. LessPass works on Tor Browser version 7.
So I close this one now.

**Closed by guillaumevincent** 2017-04-29 09:56 UTC
Labels: BUG

**Comment by alu0100892833** [comment] 2017-04-29 09:57
All right. Thank you for your help.

**Comment by edouard-lopez** [comment] 2017-07-02 18:19
Tor Browser is usually based on [Firefox ESR (Extended Support Release)](https://www.wikiwand.com/en/Firefox#/Extended_Support_Release) kind of an LTS version.

Tor Browser 7.0.1 has been [released on June 13th 2017](https://blog.torproject.org/blog/tor-browser-701-released).
