### ISSUE TITLE
[CLI] Login parameter should be required

### ISSUE THREAD

**Issue by josuecau** [lesspass/lesspass#269] opened 2017-09-02 17:05 UTC
Currently it's possible to omit the `login` parameter from the command line.
As a result, it's interpreted as the "undefined" string.
The two following commands give the same output:

    $ echo 'MyPassword' | lesspass MySite
    master password:
    gAyUi4{>h%jc(^i(

    $ echo 'MyPassword' | lesspass MySite undefined
    master password:
    gAyUi4{>h%jc(^i(

Possible fix: https://github.com/josuecau/cli/commit/4c99ba530b5813390f6dfacab29f8bb8ee53c0d8

**Comment by guillaumevincent** [comment] 2017-09-04 06:14
Hello @josuecau,
no login is a feature: https://github.com/lesspass/lesspass/issues/128
not a bug :)

but if there is no login, maybe LessPass Cli should use an empty string ''

**Comment by josuecau** [comment] 2017-09-04 08:45
My bad! I didn't see this one.
Maybe "undefined" adds more entropy than an empty string :-)

**Comment by guillaumevincent** [comment] 2017-09-04 08:52
@josuecau LessPass Pure use empty string :(
I added a bug because the expected behaviour is an empty string

**Comment by guillaumevincent** [comment] 2017-09-05 17:26
fixed in version 5.0.0

**Closed** 2017-09-05 17:26 UTC
Labels: BUG
