### ISSUE TITLE
Avoid ambiguous characters

### ISSUE THREAD

**Issue by sctfic** [lesspass/lesspass#143] opened 2017-01-18 15:25 UTC
Is it possible to have an option to avoid ambiguous characters like:
- [ 0 O o ]
- [ l I 1 | ]

**Comment by guillaumevincent** [comment] 2017-01-18 16:05
no without reducing entropy of the generated password
readable generated password in not a feature available with current algorithm implementation

**Comment by edouard-lopez** [comment] 2017-01-18 20:47
@sctfic 
* why this request? 
* Do you type your password ?
* what is the context in which you use lesspass?

**Comment by sctfic** [comment] 2017-01-19 15:07
Reduce entropy ?!  like others options --no-lowercase --no-uppercase --no-digits --no-symbols

Why my request ? Lesspass (Core) generate same password with same parameters and I use this password on external devices or in inputbox without Paste function (main computers login)

**Comment by guillaumevincent** [comment] 2017-01-19 21:35
Ok so it's a duplicate of this one https://github.com/lesspass/lesspass/issues/101

**Comment by edouard-lopez** [comment] 2017-01-20 12:44
Using a font with serif will help distinguish characters and can be local to the generated password field:

![selection_058](https://cloud.githubusercontent.com/assets/1212392/22149707/a2af5a94-df15-11e6-8101-411b7d342d00.png)

or [OpenDyslexic](http://www.dafont.com/open-dyslexic.font?text=O0o%7C1li)

![selection_060](https://cloud.githubusercontent.com/assets/1212392/22149909/88c1db6a-df16-11e6-94e1-906969dce6d4.png)

**Comment by kinahwatts** [comment] 2017-01-21 04:48
or monospace font

### `O0o | 1li`

**Comment by guillaumevincent** [comment] 2017-01-22 08:50
@edouard-lopez @kinahwatts is right and monospace font is prettier than serif font.
Will use this one

**Comment by edouard-lopez** [comment] 2017-01-24 13:55
Thanks @kinahwatts I tested on linux and `Courier New` looks good.

### OK
```
font-family: Courier New;
font-weight: bold;
```
![selection_063](https://cloud.githubusercontent.com/assets/1212392/22249746/783f83ce-e244-11e6-88c3-cbd0e52d3419.png)

### NOK
```
font-family: Courier;
font-weight: bold;
```
![selection_062](https://cloud.githubusercontent.com/assets/1212392/22249748/7af8dfd4-e244-11e6-8ece-1d3ed08422e8.png)
Lack dot in zero, seems smaller.

N.B. : remote webfont are not applicable due to the no 3rd-party policy.

**Comment by guillaumevincent** [comment] 2017-01-24 14:41
will use this one:

    font-family: Consolas,Menlo,Monaco,Lucida Console,Liberation Mono,DejaVu Sans Mono,Bitstream Vera Sans Mono,Courier New,monospace,sans-serif;

Font family from stackoverflow code tag
![image](https://cloud.githubusercontent.com/assets/943762/22251578/9ab0139a-e24b-11e6-96b5-58a229390407.png)

**Comment by guillaumevincent** [comment] 2017-01-24 14:50
Will be fix in the next version.
See https://github.com/lesspass/pure/commit/1e594ee82e16131d748460d98f2607a1c8c7d404

**Closed by guillaumevincent** 2017-01-24 14:50 UTC
Labels: idea, UX
