### ISSUE TITLE
Connected version issue!

### ISSUE THREAD

**Issue by rippie** [lesspass/lesspass#281] opened 2017-09-28 14:51 UTC
Hi all!

Thanks for LessPass first of all. After researching, I changed all my passwords with lesspass generated ones. Great tool.
Now the issue I have is that  I am using chrome and when login into connected version, I only see 2 sites there. 
Even if I save one later on, I see only 2 sites. Saved one doesn't show up. That list doesn't grow more than 2 sites no matter how many I save. Any ideas why?

Secondly, how do I delete online account?

Thanks for all inputs!

**Comment by guillaumevincent** [comment] 2017-09-29 10:54
> Even if I save one later on, I see only 2 sites. Saved one doesn't show up. That list doesn't grow more than 2 sites no matter how many I save. Any ideas why?

This is a strange issue, I can't reproduce it on my chrome.
Are you using the site or the web extension on chrome?

> Secondly, how do I delete online account?

To delete an account, send an email to `contact(at)lesspass.com` from the corresponding email in LessPass Database.

**Comment by guillaumevincent** [comment] 2017-09-29 11:18
I close this one, looks like it's related to https://github.com/lesspass/lesspass/issues/279

**Closed by guillaumevincent** 2017-09-29 11:18 UTC

**Comment by rippie** [comment] 2017-09-29 11:48
Thanks for the reply!


But I am not talking about saving multiple profiles for a single website. I'm talking about saving more than 2 websites, any websites. Like say google and hotmail and then if I want to save github, there would only be 2 websites there. Third one doesn't show up.


________________________________

**Comment by guillaumevincent** [comment] 2017-09-29 11:53
send me an email at `contact(at)lesspass.com` with the corresponding account
I will look at it

**Are you using the site or the web extension on chrome?**
Thanks
