### ISSUE TITLE
[Enhancement] Firefox addon scrolling

### ISSUE THREAD

**Issue by ghost** [lesspass/lesspass#394] opened 2019-02-19 10:19 UTC
If you click on the LessPass Firefox addon icon, the small window that appears needs to be scrolled to the right each time just to see the emoticons and far-right buttons, even if Firefox is maximized. This is quite inconvenient and can't be changed as this addon has no settings. Please make it possible for that window to appear in full size.

**Comment by edouard-lopez** [comment] 2019-02-19 11:21
**related:** #373, #165

---

Hi @zorbakus,
thanks for the feedback, could you give more info on the version you are using?

* firefox version
* lesspass version 
* a recording (with [peek](https://github.com/phw/peek), [gifcam](http://blog.bahraniapps.com/gifcam/) or equivalent) 

### My Behavior
I don't have any scroll on Firefox `66.0b8 (64-bit)` with Lesspass `3.1.2`

![lesspass-scrolling](https://user-images.githubusercontent.com/1212392/53011313-6515f580-3440-11e9-881f-0ee10346caf4.gif)

**Comment by guillaumevincent** [comment] 2019-02-20 15:58
![image](https://user-images.githubusercontent.com/943762/53104975-9372fe00-3530-11e9-8c70-8d9ab9734a7a.png)

same for me,
what is your operating system and version of Firefox?

**Comment by zorbakus** [comment] 2019-02-22 20:59
I figured out what causes the issue - hiding the addon's icon in Firefox's overflow menu. When I put it next to address bar, it displays fully. But anyway, I'm using Linux Mint 19.1 64-bit, with Firefox 65.0.1

**Comment by edouard-lopez** [comment] 2019-02-25 11:21
@zorbakus I was susptecting this was the cause as I met the issue a few months back. However, I can't reproduce with:
* Lesspass `3.1.2`
* Firefox `66.0b9` 64-bit (beta)
* Linux Mint 19 Cinnamon.

![lesspass-overflow-menu](https://user-images.githubusercontent.com/1212392/53333294-bcf7a500-38f5-11e9-95a9-7ed71409617b.gif)

Firefox seems to have fixed the issue in its next version. Either install `66.0bx` or wait for the `66.0` to be released.

**Comment by guillaumevincent** [comment] 2019-02-25 13:52
Ok we can close this one no?

**Comment by collectorgeneral** [comment] 2019-03-03 21:57
@guillaumevincent Unfortunately, the problem still persists for me and is rather annoying. I tried it on the latest firefox and on Windows/Linux. As soon as the extension is in the overfill menu, the UI decides to go bonkers. Its really odd.
![peek 2019-03-03 17-55](https://user-images.githubusercontent.com/15972594/53702469-b5486c80-3ddd-11e9-9f40-2db455542519.gif)

**Comment by guillaumevincent** [comment] 2019-03-04 08:33
@collectorgeneral which version of Firefox do you use? On Linux the latest version is version 65.

It's fixed in version 66. Install the beta or wait for the version 66. It's a Firefox bug.

**Comment by collectorgeneral** [comment] 2019-03-04 23:07
@guillaumevincent I used both 65 and 66 beta I downloaded from Mozilla. I opened Firefox using a new profile and it still does the same thing. I have not tried using the Arch Linux repo version yet, but I am not sure if it will make a difference.

**Comment by guillaumevincent** [comment] 2019-03-05 19:52
Hum,
Let me do some tests at the end of the week
Sorry for this

**Comment by guillaumevincent** [comment] 2019-07-18 19:54
I can't reproduce this one
Closing

Feel free to give me a way to reproduce it, I will try to fix it

**Closed by guillaumevincent** 2019-07-18 19:54 UTC
Labels: 🎨 ui
