### ISSUE TITLE
Unable to change password, no email received

### ISSUE THREAD

**Issue by florentulve** [lesspass/lesspass#318] opened 2018-03-06 07:37 UTC
I've forgotten my password, so I'm trying to change it but I don't received any mail in my inbox.

**Comment by guillaumevincent** [comment] 2018-03-06 08:37
![screenshot from 2018-03-06 09-35-39](https://user-images.githubusercontent.com/943762/37021985-cc09853c-2121-11e8-92da-af27e2e2f3bf.png)

Hello @florentulve, it works for me.
Can you recheck?

**Comment by florentulve** [comment] 2018-03-06 19:26
Unfortunately, it doesn't work... The adress is already known when trying to register but when I try to reset password, nothing happened.

![image](https://user-images.githubusercontent.com/2817358/37053206-d2bd1998-217b-11e8-863e-103cf77d76d6.png)

**Comment by edouard-lopez** [comment] 2018-03-07 09:34
@florentulve Did you check your spam folder?

**Comment by florentulve** [comment] 2018-03-07 11:53
Yes, I've check spam. Maybe it's somehow related to protonmail, it works with another accout with a Gmail address.

**Comment by edouard-lopez** [comment] 2018-03-07 21:37
I'm closing then. 

Feel free to re-open if you find the cause.

**Closed by edouard-lopez** 2018-03-07 21:37 UTC

**Comment by earlcray** [comment] 2019-02-03 09:46
hello all i am experiencing the same error? any fix for protonmail users?
