### ISSUE TITLE
Encrypt master password by default at sign in

### ISSUE THREAD

**Issue by kir0ul** [lesspass/lesspass#597] opened 2021-03-09 18:32 UTC
Hi there,

I noticed a difference between the Firefox add-on and the Android app at the sign in step: the Android app encrypts the master password by default but not the Firefox add-on. Would it be safer to make it the default also on the Firefox add-on?

 I have no idea how complicated it is to change this but I could consider doing a PR if there's any interest in this.

Thanks for all your work on LessPass!

**Comment by guillaumevincent** [comment] 2021-03-09 19:28
Hello,
kind of duplicate of https://github.com/lesspass/lesspass/issues/420
Yes it should be the default on the addon also.

I don't know your level, but I can guide you if you want to work on this one

https://github.com/lesspass/lesspass/tree/master/packages/lesspass-pure/src

**Comment by kir0ul** [comment] 2021-03-09 22:28
I would also say it depends how "urgent" it is, like if you need it soon, I would leave it to someone else. But in case there's no particular deadline, I can give it a try!

**Comment by guillaumevincent** [comment] 2021-03-10 07:46
@kir0ul no particular deadline. thank you

**Comment by kir0ul** [comment] 2021-03-18 05:35
I was wondering if Cypress is still being used for your e2e testing?

**Comment by guillaumevincent** [comment] 2021-03-18 07:15
yes but I disabled it for the CICD part.
I need to enable it again

**Comment by guillaumevincent** [comment] 2021-03-19 22:33
Tests end to end are green now

**Closed** 2021-03-27 23:32 UTC
